apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wj0lh0hwj-python 
  janus-idp.io/tekton: wj0lh0hwj-python
  backstage.io/kubernetes-id: wj0lh0hwj-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wj0lh0hwj-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  