apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: wj0lh0hwj-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:d4c182bb72437874dc81e091bcf8c219f721d477@sha256:9775b548d9278d52124b09e44a7e003fe5f32bcd15ab7fca9b267be1536fdde7
          name: container-image
