apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wj0lh0hwj-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wj0lh0hwj-python 
  name: wj0lh0hwj-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wj0lh0hwj-python 
